# ===============================
# 🔹 Universal Downloader Bot — Render deploy konfiguratsiyasi
# ===============================

services:
  - type: web
    name: universal-downloader-bot
    env: python
    region: oregon
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py

    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: AUDD_API_TOKEN
        sync: false
      - key: PORT
        value: 10000
